name: Use Docker Container as Database

on: 
  push:
    branches:
      - master

jobs:
  job1:
    runs-on: ubuntu-latest

    services:
      mysql_service:
        image: mysql:latest
        ports:
          - 3306:3306 
        env:
          MYSQL_HOST: localhost 
          MYSQL_PORT: 3306
          MYSQL_DATABASE: cybage
          MYSQL_USER: test1
          MYSQL_ROOT_PASSWORD: root
          MYSQL_PASSWORD: password

    steps:
            
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
          
      - name: Cache the maven dependency
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Mvn Clean Test
        env:
          MYSQL_HOST: localhost  # Set the host to localhost for the service container
          MYSQL_PORT: 3306
          MYSQL_DATABASE: cybage
          MYSQL_USER: test1
          MYSQL_PASSWORD: password

        run: mvn clean install 


